
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven CI feature branches

on:
  push:
    branches:
    - 'feature/**'
    - 'bugfix/**'
    - 'hotfix/**'
    - 'dependabot/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: maven
    - uses: s4u/maven-settings-action@v2.8.0
      with:
        servers: |
          [{
              "id": "github-banzai",
              "username": "${{ secrets.GH_PACKAGE_USER }}",
              "password": "${{ secrets.GH_PACKAGE_TOKEN }}"
          }]
    - name: Maven verify
      run: mvn -B verify
    - name: Maven run tests
      run: mvn -B test
    - name: Maven build package
      run: mvn -B package -Dmaven.test.skip
